services:
  backend:
    build: .
    container_name: finance-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development